# Generated by Django 5.2.7 on 2025-10-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('session_start_year', models.PositiveSmallIntegerField()),
                ('session_end_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='catalog.program')),
            ],
            options={
                'ordering': ['-session_start_year', 'program__name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CohortLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('semesters', models.PositiveSmallIntegerField(default=2)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.level')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='institution_admin.programcohort')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='programcohort',
            constraint=models.UniqueConstraint(fields=('program', 'session_start_year', 'session_end_year'), name='uniq_program_session'),
        ),
        migrations.AddConstraint(
            model_name='cohortlevel',
            constraint=models.UniqueConstraint(fields=('cohort', 'position'), name='uniq_cohort_position'),
        ),
        migrations.AddConstraint(
            model_name='cohortlevel',
            constraint=models.UniqueConstraint(fields=('cohort', 'level'), name='uniq_cohort_level'),
        ),
    ]
