# Generated by Django 5.2.7 on 2025-10-29 15:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_slots_per_cohort', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_daily_slots_per_lecturer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_consecutive_slots_lecturer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_constraints', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('session_start_year', models.PositiveSmallIntegerField()),
                ('session_end_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='catalog.program')),
            ],
            options={
                'ordering': ['-session_start_year', 'program__name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('capacity_need', models.PositiveIntegerField(blank=True, null=True)),
                ('room_features', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.level')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.academicterm')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='institution_admin.programcohort')),
            ],
            options={
                'ordering': ['cohort_id', 'level_id', 'semester', 'course_id'],
            },
        ),
        migrations.CreateModel(
            name='CohortLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('semesters', models.PositiveSmallIntegerField(default=2)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.level')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='institution_admin.programcohort')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PublishedTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_snapshots', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['day', 'slot_index'],
            },
        ),
        migrations.CreateModel(
            name='RoomBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='catalog.room')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_blackouts', to='catalog.academicterm')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_blackouts', to='institution_admin.slot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_name', models.CharField(blank=True, default='', max_length=120)),
                ('course_code', models.CharField(blank=True, default='', max_length=32)),
                ('course_title', models.CharField(blank=True, default='', max_length=200)),
                ('cohort_label', models.CharField(blank=True, default='', max_length=150)),
                ('level_name', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution_admin.courseoffering')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='institution_admin.publishedtimetable')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution_admin.slot')),
            ],
            options={
                'ordering': ['day', 'slot_index', 'cohort_label', 'course_code'],
            },
        ),
        migrations.CreateModel(
            name='LecturerBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_blackouts', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_blackouts', to='catalog.academicterm')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_blackouts', to='institution_admin.slot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_blackouts', to='catalog.academicterm')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='institution_admin.programcohort')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_blackouts', to='institution_admin.slot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('load_share', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='institution_admin.courseoffering')),
            ],
            options={
                'ordering': ['offering_id', 'role', 'position', '-active', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_days', models.JSONField(default=list)),
                ('first_slot_start', models.TimeField()),
                ('slot_length_min', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)])),
                ('slots_per_day', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('break_slots', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='timegrid', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-term_id'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='institution_admin.courseoffering')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='catalog.room')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='institution_admin.slot')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['term_id', 'slot_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='programcohort',
            constraint=models.UniqueConstraint(fields=('program', 'session_start_year', 'session_end_year'), name='uniq_program_session'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('term', 'cohort', 'level', 'semester', 'course'), name='uniq_offering_term_cohort_level_sem_course'),
        ),
        migrations.AddConstraint(
            model_name='cohortlevel',
            constraint=models.UniqueConstraint(fields=('cohort', 'position'), name='uniq_cohort_position'),
        ),
        migrations.AddConstraint(
            model_name='cohortlevel',
            constraint=models.UniqueConstraint(fields=('cohort', 'level'), name='uniq_cohort_level'),
        ),
        migrations.AddConstraint(
            model_name='publishedtimetable',
            constraint=models.UniqueConstraint(fields=('term', 'version'), name='uniq_term_version_snapshot'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('term', 'day', 'slot_index')},
        ),
        migrations.AlterUniqueTogether(
            name='roomblackout',
            unique_together={('term', 'slot', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='lecturerblackout',
            unique_together={('term', 'slot', 'lecturer')},
        ),
        migrations.AlterUniqueTogether(
            name='cohortblackout',
            unique_together={('term', 'slot', 'cohort')},
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('offering', 'role', 'position'), name='uniq_role_position_per_offering'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('offering', 'slot'), name='uniq_offering_slot'),
        ),
    ]
