# Generated by Django 5.2.7 on 2025-10-30 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programcohort',
            name='is_auto',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='CohortAutoCreateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_days', models.PositiveIntegerField(default=365)),
                ('next_creation_date', models.DateField()),
                ('auto_enroll_students', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-next_creation_date'],
            },
        ),
        migrations.AddField(
            model_name='programcohort',
            name='auto_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution_admin.cohortautocreateconfig'),
        ),
    ]
