# Generated by Django 5.2.7 on 2025-10-26 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='institution_admin.programcohort')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('cohort', 'code')},
            },
        ),
    ]
