# Generated by Django 5.2.7 on 2025-10-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_course'),
        ('institution_admin', '0002_cohortstream'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('capacity_need', models.PositiveIntegerField(blank=True, null=True)),
                ('room_features', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cohort_id', 'level_id', 'semester', 'course_id', 'stream_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='cohortstream',
            options={'ordering': ['code', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='cohortstream',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cohortstream',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='cohortstream',
            constraint=models.UniqueConstraint(fields=('cohort', 'code'), name='uniq_stream_code_per_cohort'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='institution_admin.programcohort'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.course'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.level'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='institution_admin.cohortstream'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.academicterm'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('term', 'cohort', 'level', 'semester', 'course', 'stream'), name='uniq_offering_term_cohort_level_sem_course_stream'),
        ),
    ]
