# Generated by Django 5.2.7 on 2025-10-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_admin', '0002_programcohort_is_auto_cohortautocreateconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohortautocreateconfig',
            options={'ordering': ['-next_creation_at', '-next_creation_date']},
        ),
        migrations.AddField(
            model_name='cohortautocreateconfig',
            name='frequency_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohortautocreateconfig',
            name='next_creation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cohortautocreateconfig',
            name='next_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
