# Generated by Django 5.2.7 on 2025-10-26 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_admin', '0003_courseoffering_alter_cohortstream_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('CO', 'Co-lecturer'), ('TA', 'Teaching Assistant'), ('BACKUP', 'Backup')], default='PRIMARY', max_length=16)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('load_share', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='institution_admin.courseoffering')),
            ],
            options={
                'ordering': ['offering_id', 'role', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('offering', 'lecturer'), name='uniq_assignment_offering_lecturer'), models.UniqueConstraint(fields=('offering', 'role', 'position'), name='uniq_assignment_role_position')],
            },
        ),
    ]
