# Generated by Django 5.2.7 on 2025-10-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_admin', '0003_alter_cohortautocreateconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortautocreateconfig',
            name='label_custom_template',
            field=models.CharField(blank=True, default='', help_text='Used when label_mode=CUSTOM. Use tokens: {year},{month_num},{month_name},{day},{hour},{minute},{second},{dept},{program},{suffix}', max_length=200),
        ),
        migrations.AddField(
            model_name='cohortautocreateconfig',
            name='label_mode',
            field=models.CharField(choices=[('YEARLY', 'Yearly (year)'), ('MONTHLY', 'Monthly (month-year)'), ('DAILY', 'Daily (date-month-year)'), ('PRECISE', 'Precise (hour-minute-date-month-year)'), ('CUSTOM', 'Custom (use template)')], default='YEARLY', max_length=12),
        ),
    ]
