# Generated by Django 5.2.7 on 2025-10-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_admin', '0004_teachingassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='teachingassignment',
            name='uniq_assignment_offering_lecturer',
        ),
        migrations.RemoveConstraint(
            model_name='teachingassignment',
            name='uniq_assignment_role_position',
        ),
    ]
