# Generated by Django 5.2.7 on 2025-10-26 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_admin', '0005_alter_teachingassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'ordering': ['offering_id', 'role', 'position', '-active', 'id']},
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='role',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('offering', 'role', 'position'), name='uniq_role_position_per_offering'),
        ),
    ]
