# Generated by Django 5.2.7 on 2025-10-26 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_course'),
        ('institution_admin', '0006_alter_teachingassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['day', 'slot_index'],
                'unique_together': {('term', 'day', 'slot_index')},
            },
        ),
        migrations.CreateModel(
            name='TimeGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_days', models.JSONField(default=list)),
                ('first_slot_start', models.TimeField()),
                ('slot_length_min', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)])),
                ('slots_per_day', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('break_slots', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='timegrid', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-term_id'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='institution_admin.courseoffering')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='catalog.room')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='institution_admin.slot')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['term_id', 'slot_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('offering', 'slot'), name='uniq_offering_slot')],
            },
        ),
    ]
