# Generated by Django 5.2.7 on 2025-10-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_course'),
        ('institution_admin', '0007_slot_timegrid_timetableentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_slots_per_cohort', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_daily_slots_per_lecturer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_consecutive_slots_lecturer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_constraints', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='institution_admin.programcohort')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_blackouts', to='institution_admin.slot')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='institution_admin.cohortstream')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_blackouts', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('term', 'slot', 'cohort', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='LecturerBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_blackouts', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_blackouts', to='institution_admin.slot')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_blackouts', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('term', 'slot', 'lecturer')},
            },
        ),
        migrations.CreateModel(
            name='RoomBlackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='catalog.room')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_blackouts', to='institution_admin.slot')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_blackouts', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('term', 'slot', 'room')},
            },
        ),
    ]
