#!/usr/bin/env python3
"""
scripts/rename_superadmin.py

Usage:
  python scripts/rename_superadmin.py

Creates a git branch, does repo-wide textual rename of "institution_owner" -> "institution_owner"
(case-aware), skips migrations and .git and virtual envs. Commits changes for review.

IMPORTANT: run on a clean working tree and after backing up DB.
"""
import re
import subprocess
import sys
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent
SKIP_DIRS = {".git", "migrations", "venv", "env", "__pycache__", ".venv", "node_modules"}

# Patterns and replacements (order matters: longer first)
REPLACEMENTS = [
    # Class / CamelCase
    (r"\bSuperAdmin\b", "InstitutionOwner"),
    (r"\bSUPERADMIN\b", "INSTITUTION_OWNER"),
    (r"\bsuperadmin\b", "institution_owner"),
    # Spaced UI forms
    (r"Institution Owner", "Institution Owner"),
    (r"INSTITUTION OWNER", "INSTITUTION OWNER"),
    (r"institution owner", "institution owner"),
    # Single/double-quoted variations
    (r"'InstitutionOwner'", "'InstitutionOwner'"),
    (r'"InstitutionOwner"', '"InstitutionOwner"'),
    (r"'institution_owner'", "'institution_owner'"),
    (r'"institution_owner"', '"institution_owner"'),
    # Constants/ENV style
    (r"\bSUPER_ADMIN\b", "INSTITUTION_OWNER"),
]

BINARY_FILE_EXTS = {
    ".png", ".jpg", ".jpeg", ".gif", ".woff", ".woff2", ".ttf", ".eot", ".pdf", ".zip"
}

def should_skip(path: Path) -> bool:
    # skip directories and binary files
    for p in path.parts:
        if p in SKIP_DIRS:
            return True
    if path.suffix.lower() in BINARY_FILE_EXTS:
        return True
    return False

def git(cmd):
    return subprocess.check_output(["git"] + cmd, cwd=ROOT).decode().strip()

def main():
    # Ensure clean git tree
    status = git(["status", "--porcelain"])
    if status:
        print("Please commit or stash your changes first. Git status is not clean.")
        print(status)
        sys.exit(1)

    # create branch
    branch_name = f"rename-institution_owner-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
    print(f"Creating branch: {branch_name}")
    git(["checkout", "-b", branch_name])

    changed_files = []
    skipped = []

    for path in ROOT.rglob("*"):
        if path.is_dir():
            continue
        if should_skip(path):
            skipped.append(str(path.relative_to(ROOT)))
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:
            skipped.append(str(path.relative_to(ROOT)))
            continue

        new_text = text
        for pattern, repl in REPLACEMENTS:
            new_text = re.sub(pattern, repl, new_text)

        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            changed_files.append(str(path.relative_to(ROOT)))

    if not changed_files:
        print("No occurrences were changed. Nothing to commit.")
        print("Skipped (sample):", skipped[:10])
        return

    # git add & commit
    git(["add", "."])
    commit_msg = "chore(rename): institution_owner → institution_owner (automated rename)\n\n" + \
                 "This commit was generated by scripts/rename_superadmin.py. Review carefully."
    git(["commit", "-m", commit_msg])
    print("Committed changes to branch:", branch_name)
    print("Changed files:", len(changed_files))
    for f in changed_files[:40]:
        print("  ", f)
    if len(changed_files) > 40:
        print("  ... (more)")

    print("\nIMPORTANT: Review the changes now (git diff, open PR). Do not push without review.")
    print("Skipped files (sample):", skipped[:10])

if __name__ == "__main__":
    main()
