# Generated by Django 5.2.7 on 2025-10-30 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_course'),
        ('institution_admin', '0004_cohortautocreateconfig_label_custom_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerBlackoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('lecturer_note', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('admin_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackout_requests', to=settings.AUTH_USER_MODEL)),
                ('reschedule_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blackout_requests', to='institution_admin.timetableentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_blackout_requests', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_blackout_requests', to='institution_admin.slot')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_blackout_requests', to='catalog.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lecturer', 'term', 'slot', 'status'], name='lecturers_l_lecture_d29d87_idx')],
            },
        ),
    ]
